version: '3.3'

services:
  nginx:
    image: nginx
    container_name: nginx-dev
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./www:/usr/share/nginx/html

  php:
    image: devel-php:latest
    container_name: php-dev
    volumes:
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./www:/usr/share/nginx/html

  mysql:
    image: mysql:5.7
    container_name: mysql-dev
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass

volumes:
    data:
